version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: shark-nodejs-image
    container_name: shark-nodejs-container
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "80:8080"
    networks:
      - app-network
    depends_on: 
      - mongo
    command: node app.js 
    
  mongo:
    image: mongo:4.1.8-xenial
    container_name: shark-mongo-container
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network  
    ports: 
      - "27017:27017"

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules: 